package rules;

import com.smit.compliq.entity.Invoice;
import com.smit.compliq.entity.Vendor;
import com.smit.compliq.enums.VendorStatus;
import com.smit.compliq.drools.ValidationContext;
import com.smit.compliq.drools.ValidationIssue;
import com.smit.compliq.enums.Severity;

global ValidationContext validationContext;

rule "GST Format Validation"
when
    $invoice : Invoice($gst : gstNumber)
    eval($gst != null)
    eval(
        !$gst.matches(
            "^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[A-Z0-9]{1}Z[A-Z0-9]{1}$"
        )
    )
then
    validationContext.getValidationResult().addViolation(
        new ValidationIssue("GST Format Validation", "Invalid GST Number format", Severity.HIGH));
end

rule "Vendor Must Be Active"
when
    $vendor : Vendor(vendorStatus != VendorStatus.ACTIVE)
then
    validationContext.getValidationResult().addViolation(
        new ValidationIssue("Vendor Must Be Active", "Vendor is not active", Severity.HIGH));
end